from local/c7-systemd

RUN yum update -y
RUN yum install expect -y
RUN yum install wget -y
RUN yum install epel-release -y
RUN wget http://rpms.remirepo.net/enterprise/remi-release-7.rpm
RUN rpm -Uvh remi-release-7.rpm
RUN yum install yum-utils -y
RUN yum-config-manager --enable remi-php72 -y
RUN yum --enablerepo=remi,remi-php72 install php-fpm php-common -y
RUN yum --enablerepo=remi,remi-php72 install php-opcache php-pecl-apcu php-cli php-bcmath php-imap php-xmlrpc php-soap  php-zip php-pear php-pdo php-mysqlnd php-pecl-redis php-pecl-memcache php-pecl-memcached php-gd php-mbstring php-mcrypt php-xml -y
RUN systemctl enable php-fpm.service
RUN useradd -u 1010 -U  wordpress
COPY www.conf /etc/php-fpm.d/www.conf
COPY php.ini /etc/php.ini


